import * as path from "path";
import { Handler } from "express";
import { createLogger } from "../logging";
import { fetchFileList, generateHash } from "./utils";

const HASH_UNSET = "HASH_UNSET";

/**
 * Static serving middleware that sends md5 hash etags as a workaround for GAE being incompatible
 * with weak etags generated by express.static middleware.
 *
 * - On initialisation a list of all valid files is generated
 * - On first request for each file the md5 hash is generated and then cached for later use
 *
 * This is only intended to serve files like index.html and manifest.json that cannot
 * be served by the built in GAE static file handlers:
 * (https://cloud.google.com/appengine/docs/standard/nodejs/serving-static-files).
 *
 * @example
 * app.use(serveStaticWithEtag({ root: "public" })
 */
export const serveStaticWithEtag = (options: { root: string }): Handler => {
  const logger = createLogger("gaeServeStatic");
  const rootFolder = `${__dirname}/${options.root}`;
  const validFiles: Record<string, string> = {};

  fetchFileList(rootFolder).then((allFiles) => {
    allFiles.forEach((file) => (validFiles[file] = HASH_UNSET));
    logger.info("Serving static files: ", Object.keys(validFiles));
  });

  return async (req, res, next) => {
    const requestPath = path.join(req.baseUrl, req.path);
    const fullFilePath = path.join(rootFolder, requestPath);

    if (validFiles[requestPath]) {
      if (validFiles[requestPath] === HASH_UNSET) {
        logger.debug(`Generating md5 hash for file ${fullFilePath}`);
        validFiles[requestPath] = await generateHash(fullFilePath);
      }

      logger.info(`Sending file ${fullFilePath}`);
      const etag = validFiles[requestPath];
      return res.sendFile(fullFilePath, { headers: { etag } }, (err) => {
        return err ? next(err) : next();
      });
    }

    next();
  };
};
